/** Contextual tooltips for each spec file's fields, shown in the editor UI */
export const FIELD_TOOLTIPS: Record<string, Record<string, string>> = {
  "features.json": {
    id: "Identifiant unique de la feature (convention : feature.*). Immutable une fois créé.",
    label: "Nom affiché dans le wizard et les devis",
    domain: "Domaine fonctionnel (CONTENT, ECOMMERCE, ANALYTICS…). Utilisé pour grouper les features dans le wizard.",
    uiOnly: "Si true, la feature est purement visuelle (thème) et n'impacte pas la catégorie de prix",
    type: "Type de la feature (CMS, ECOMMERCE, THEME…). Utilisé dans le moteur de décision.",
    description: "Description courte de la feature — affichée dans le wizard et les documents de spécification.",
  },
  "commercial.json": {
    basePackageBandsByCategory: "Fourchettes de prix de base par catégorie projet. Affiché dans le devis initial.",
    maintenanceByCategory: "Tarifs de maintenance mensuelle par catégorie. Affiché dans la partie récurrente du devis.",
    deployFees: "Frais de déploiement initial par type d'hébergement (inclut variantes headless)",
    hostingCosts: "Coûts d'hébergement mensuels estimés par cible de déploiement (inclut variantes headless)",
    saasCosts: "Coûts SaaS mensuels pour les plateformes (Shopify, BigCommerce…)",
    stackDeployCompat: "Matrice de compatibilité stack ↔ type de déploiement",
    annexCosts: "Coûts annexes (domaine, email, stockage…) intégrés au récapitulatif devis",
    rules: "Règles tarifaires appliquées par le moteur de décision",
    pluginRecurringCosts: "Paramètres de calcul des coûts récurrents plugins",
    description: "Description du poste tarifaire — contexte métier et positionnement pour le commercial",
    scope: "Périmètre des prestations incluses dans ce poste",
    splitPrestataire: "Part du prestataire sur le montant mensuel (le reste revient au client en coût d'infra)",
    cost: "Coût forfaitaire unique en euros",
    monthly: "Coût mensuel récurrent en euros",
  },
  "stack-profiles.json": {
    families: "Familles de stack (CMS simple, e-commerce, headless…). Chaque famille a un prix de base et un plancher de maintenance.",
    profiles: "Profils de stack concrets (wordpress-minimal, shopify-standard…). Chaque profil appartient à une famille et a des capacités spécifiques.",
    implementationMapping: "Mapping CMS → profil de stack par défaut. Utilisé quand le moteur choisit un CMS.",
    projectFamilyMapping: "Mapping type de projet → famille de stack. Utilisé pour le premier tri.",
    description: "Description de la famille ou du profil — résume le positionnement technique et le cas d'usage cible",
  },
  "modules.json": {
    id: "Identifiant unique du module (convention : module.*)",
    label: "Nom affiché dans le devis et le wizard",
    targetCategory: "Catégorie cible (CAT0–CAT4). Le module sera recommandé pour les projets de cette catégorie et au-dessus.",
    priceSetupMin: "Prix setup minimum en € (installation + configuration)",
    priceSetupMax: "Prix setup maximum en €",
    priceMonthlyMin: "Coût mensuel minimum en € (maintenance spécifique)",
    priceMonthlyMax: "Coût mensuel maximum en €",
    jsMultiplier: "Multiplicateur appliqué si l'implémentation est en JavaScript (Next.js, Nuxt…)",
    ciImpact: "Impact sur l'indice de complexité (axes SA, DE, CB, SD)",
    isStructurant: "Le module change la catégorie du projet → impact majeur sur le devis",
    description: "Description détaillée du module — ce qu'il fait, pourquoi du dev custom, et les limitations des plugins existants",
    pluginInsufficiencyRationale: "Justification de pourquoi un plugin standard ne suffit pas (cross-CMS, CI/maintenance, gouvernance)",
    group: "Groupe fonctionnel du module (ecommerce, metier, contenu, technique)",
  },
  "cms.json": {
    kind: "Type de CMS : orienté contenu, e-commerce, SaaS, ou headless",
    editorialModel: "Modèle éditorial : natif (WYSIWYG intégré) ou configurable (headless)",
    extensionModel: "Modèle d'extension : plugin, app, module, ou custom",
    description: "Description synthétique du CMS — positionnement, cas d'usage principal et points forts",
  },
  "shared-socle.json": {
    baselineRequirements: "Exigences techniques de base appliquées à tous les projets (sécurité, backup, monitoring…)",
    stackDeltas: "Adaptations spécifiques par CMS des exigences de base",
    commercialReferences: "Références croisées vers les données tarifaires dans commercial.json",
  },
  "capability-matrix.json": {
    matrix: "Matrice feature × CMS. Pour chaque feature, définit comment chaque CMS la supporte (natif, plugin, module, custom).",
  },
  "decision-rules.json": {
    classificationEnum: "Les 5 niveaux de classification possibles pour une feature/CMS",
    decisionFlow: "Séquence canonique de décision du moteur",
    economicRules: "Règles tarifaires : prix de base, maintenance, garde-fous",
    constraints: "Contraintes de qualification projet (trafic, produits, sensibilité…)",
    complexityIndex: "Formule et seuils pour calculer l'indice de complexité → catégorie",
    invariants: "Règles métier non négociables",
    backendFamilies: "Familles de backend avec coefficients de coût",
  },
  "plugins.json": {
    plugins: "Catalogue des plugins/apps avec compatibilité CMS et tarification récurrente",
    pricingMode: "FREE = gratuit, PAID = payant, MIXED = freemium",
    description: "Description courte du plugin — affichée dans les devis et la documentation",
    priceMonthlyMin: "Coût mensuel minimum estimé du plugin",
    priceMonthlyMax: "Coût mensuel maximum estimé du plugin",
    cmsIds: "CMS compatibles avec ce plugin",
    featureIds: "Features couvertes par ce plugin",
  },
  "infra-services.json": {
    categories: "Catégories de services infra (monitoring, cache, DB tools, search, dev tools)",
    services: "Catalogue des briques infra optionnelles avec coûts et contraintes",
    setupCost: "Coût one-shot de configuration et intégration du service",
    monthlyCost: "Surcoût mensuel estimé (ressources VPS supplémentaires)",
    containers: "Images Docker nécessaires pour faire tourner le service",
    requiresDocker: "Si true, le service ne peut tourner que sur un déploiement Docker/VPS",
    minMaintenanceCat: "Catégorie de maintenance minimum requise (CAT0 = basique, CAT4 = premium)",
    hostingImpact: "Impact sur les ressources VPS : RAM supplémentaire nécessaire",
    description: "Description du service — rôle, alternative SaaS et cas d'usage",
  },
};
