// ── French display labels for the spec editor UI ──
// Centralizes all UI strings used across renderers.

export const LABELS = {
  // ── Common ──
  all: "Tous",
  allModes: "Tous modes",
  search: "Rechercher",
  noResult: "Aucun résultat",
  fields: "champs",
  modified: "Modifié",
  save: "Enregistrer",
  saving: "Enregistrement…",
  saved: "Enregistré",
  back: "Retour",
  copy: "Copier",
  format: "Formater",
  reload: "Actualiser",
  lines: "lignes",
  keys: "clés",
  editor: "Édition",
  rawJson: "JSON",
  doc: "Documentation",
  detailedView: "Vue détaillée",

  // ── Features ──
  features: {
    filterPlaceholder: (count: number) =>
      `Rechercher (${count} fonctionnalité${count > 1 ? "s" : ""})…`,
    allDomains: "Tous domaines",
    allTypes: "Tous types",
    noFeature: "Aucune fonctionnalité trouvée",
    domain: "Domaine",
    type: "Type",
    uiOnly: "Interface seule",
    uiOnlyHint: "Fonctionnalité purement visuelle (thème) — n'impacte pas la catégorie de prix",
    functionalHint: "Fonctionnalité métier — impacte la catégorie et le prix du projet",
    label: "Libellé",
    labelHint: "Nom affiché dans le wizard et les devis",
    description: "Description",
    descriptionHint:
      "Description courte de la fonctionnalité — affichée dans le wizard et les documents de spécification",
    id: "Identifiant",
    domainHint: "Domaine fonctionnel — regroupe les fonctionnalités dans le wizard",
    typeHint: "Type technique de la fonctionnalité — utilisé par le moteur de décision",
    dependencies: "Dépendances",
    dependenciesHint: "Identifiants des fonctionnalités requises pour activer cette fonctionnalité",
    tags: "Tags",
    tagsHint: "Mots-clés pour la recherche et le tri",
    footer: (total: number, uiOnly: number) =>
      `${total} fonctionnalités dont ${uiOnly} d'interface seule`,
  },

  // ── Capability Matrix ──
  matrix: {
    title: "Matrice de capacité",
    filterPlaceholder: "Filtrer les fonctionnalités…",
    filterPlaceholderAccessible: "Filtrer les fonctionnalités…",
    classFilter: "Classification",
    allClassifications: "Toutes",
    footer: (features: number, cms: number) =>
      `${features} fonctionnalités × ${cms} CMS`,
    footerHint: "Cliquez sur une cellule pour changer la classification",
    noFeature: "Aucune fonctionnalité trouvée",
    summary: {
      native: "Natif",
      plugin: "Plugin",
      module: "Module",
      custom: "Sur mesure",
      theme: "Thème",
    },
  },

  // ── Modules ──
  modules: {
    filterPlaceholder: (count: number) =>
      `Rechercher (${count} module${count > 1 ? "s" : ""})…`,
    allGroups: "Tous groupes",
    noModule: "Aucun module trouvé",
    label: "Libellé",
    group: "Groupe",
    category: "Catégorie cible",
    minCategory: "Catégorie min",
    requalifiesTo: "Requalifie vers",
    structurant: "Structurant",
    structurantHint: "Module structurant — change la catégorie du projet et a un impact majeur sur le devis",
    setupPrice: "Prix setup",
    monthlyPrice: "Coût mensuel",
    jsMultiplier: "Multiplicateur JS",
    jsMultiplierHint: "Coefficient multiplicateur appliqué si le projet utilise un framework JavaScript (Next.js, Nuxt…)",
    splitSetup: "Part prestataire setup",
    splitMonthly: "Part prestataire mensuel",
    details: "Sous-composants",
    features: "Fonctionnalités",
    ciImpact: "Impact complexité",
    tiers: "Paliers",
    description: "Description",
    whyNotPlugin: "Pourquoi pas un plugin ?",
    footer: (total: number, structurant: number) =>
      `${total} modules dont ${structurant} structurants`,
  },

  // ── Plugins ──
  plugins: {
    filterPlaceholder: (count: number) =>
      `Rechercher (${count} plugin${count > 1 ? "s" : ""})…`,
    pricingMode: "Mode tarif",
    billingCycle: "Cycle facturation",
    billingCycleHint: "Cycle de facturation du vendeur : mensuel, annuel (licence), achat unique ou à l'usage.",
    priceAnnualLabel: "Prix annuel",
    priceOneTimeLabel: "Prix achat",
    renewalDiscount: "Réduction 2 ans",
    amortization: "Amortissement",
    monthlyCost: "Coût mensuel",
    billingNotes: "Notes facturation",
    cmsCompat: "CMS compatibles",
    features: "Fonctionnalités",
    free: "Gratuit",
    paid: "Payant",
    mixed: "Mixte (freemium)",
    notDefined: "Non défini",
    noPlugin: "Aucun plugin trouvé",
    total: "Total",
    perMonth: "€/mois",
    perYear: "€/an",
    oneShot: "€ one-shot",
  },

  // ── Commercial ──
  commercial: {
    noData: "Aucune donnée commerciale",
    description: "Description",
    scope: "Périmètre inclus",
    cost: "Coût",
    monthly: "Mensuel",
    range: "Fourchette",
    from: "À partir de",
    to: "Jusqu'à",
    splitPrestataire: "Part prestataire",
    category: "Catégorie",
    deployTarget: "Cible déploiement",
    compatibleStacks: "Stacks compatibles",
    min: "Min",
    max: "Max",
    perMonth: "€/mois",
    oneShot: "€ one-shot",
    totalSetupRange: "Fourchette setup totale",
    totalMaintenanceRange: "Fourchette maintenance",
    footer: (sections: number) => `${sections} sections commerciales`,
    annex: {
      domainYearlyRange: "Domaine (annuel)",
      domainYearlyRangeHint: "Fourchette du coût annuel de nom de domaine",
      emailMonthlyRange: "Email professionnel (mensuel)",
      emailMonthlyRangeHint: "Fourchette du coût mensuel pour les services email",
      storageMonthlyRange: "Stockage (mensuel)",
      storageMonthlyRangeHint: "Fourchette du coût mensuel de stockage additionnel",
    } as Record<string, string>,
  },

  // ── Stack Profiles ──
  stackProfiles: {
    tabs: {
      families: "Familles",
      profiles: "Profils",
      implMapping: "Mapping CMS",
      familyMapping: "Mapping projet",
    },
    families: {
      title: "Familles de stack",
      hint: "Regroupements tarifaires par type de stack (CMS simple, e-commerce, headless…)",
      basePrice: "Prix de base",
      basePriceLabel: "Libellé prix",
      maintenanceFloor: "Plancher maintenance",
      maintenanceFloorHint: "Index minimum de plan de maintenance recommandé",
      description: "Description",
      noFamily: "Aucune famille",
    },
    profiles: {
      title: "Profils de stack",
      hint: "Profils concrets (wordpress, shopify, nextjs…). Chaque profil référence une famille et a des capacités spécifiques.",
      filterPlaceholder: (count: number) =>
        `Rechercher (${count} profil${count > 1 ? "s" : ""})…`,
      allFamilies: "Toutes familles",
      family: "Famille",
      capabilities: "Capacités",
      hostingCompat: "Hébergement compatible",
      complexityFactor: "Facteur complexité",
      complexityFactorHint: "Multiplicateur de coût appliqué au prix de base de la famille",
      maintenanceFloorIndex: "Index maintenance",
      maintenanceFloorIndexHint: "Index du plan de maintenance minimum recommandé",
      legacyTechStack: "Stack historique",
      legacyTechStackHint: "Identifiant historique de stack utilisé pour le mapping CMS",
      pluginEcosystem: "Écosystème d’extensions",
      pluginEcosystemHint: "Le stack dispose d'un écosystème d'extensions ou de plugins",
      summary: "Résumé",
      pricingNotes: "Notes tarifaires",
      noProfile: "Aucun profil trouvé",
      footer: (total: number, families: number) =>
        `${total} profils dans ${families} familles`,
    },
    implMapping: {
      title: "Correspondance CMS → Profil",
      hint:
        "Quand le moteur choisit un CMS, cette correspondance détermine le profil de stack à utiliser",
      cmsKey: "Clé CMS",
      profileId: "Profil associé",
    },
    familyMapping: {
      title: "Correspondance type de projet → Famille",
      hint:
        "Premier tri : associe un type de projet à une famille de stack pour la tarification",
      projectType: "Type projet",
      familyId: "Famille associée",
    },
  },

  // ── Decision Rules ──
  decision: {
    tabs: {
      complexity: "Complexité",
      economics: "Économie",
      constraints: "Contraintes",
      invariants: "Invariants",
      backend: "Backend",
    },
    complexity: {
      title: "Indice de complexité",
      hint: "Formule, poids et seuils pour catégoriser automatiquement un projet (CAT0→CAT4)",
      weights: "Poids des axes",
      weightsHint: "Poids de chaque axe dans le calcul CI. Modifie l'importance relative de chaque dimension.",
      thresholds: "Seuils de catégorisation",
      thresholdsHint: "Seuils CI → catégorie. Définit quelle valeur CI mène à quelle catégorie projet.",
      formulaHint: "Formule utilisée pour calculer l'indice de complexité d'un projet",
    },
    economics: {
      title: "Règles économiques",
      hint: "Tarifs de base, maintenance, garde-fous et règles de cohérence tarifaire",
      basePricing: "Tarifs de base par catégorie",
      basePricingHint: "Prix de base du package par catégorie. Utilisé pour générer les fourchettes de devis.",
      maintenance: "Maintenance mensuelle par catégorie",
      maintenanceHint: "Tarifs de maintenance mensuelle par catégorie. Affichés au client dans le devis récurrent.",
      guardrails: "Garde-fous positionnement",
      guardrailsHint: "Garde-fous tarifaires pour éviter des incohérences dans le positionnement prix",
      coherence: "Cohérence tarifaire",
      coherenceHint: "Règles de cohérence prix imposées au moteur de décision",
      startingFrom: "À partir de",
    },
    constraints: {
      title: "Contraintes projet",
      hint: "Options de qualification projet (trafic, produits, sensibilité…). Chaque valeur peut imposer une catégorie minimum.",
      constraintHint: "Contrainte de projet utilisée par le moteur pour ajuster la catégorie minimale recommandée",
      minCatHint: (val: string) => `Catégorie minimale quand ${val} est sélectionné`,
    },
    invariants: {
      title: "Invariants",
      hint: "Règles métier non négociables vérifiées en amont par le moteur",
    },
    backend: {
      title: "Familles backend",
      hint: "Types de backend avec coefficients de coût appliqués quand un backend custom est requis",
      coefficient: "Coefficient",
      coefficientHint: "Coefficient multiplicateur appliqué au coût de développement pour ce type de backend",
      opsHeavy: "Coefficient ops heavy",
      opsHeavyHint: "Surcoût appliqué quand le backend est classifié 'ops heavy' (CI/CD complexe, orchestration)",
    },
  },

  // ── Infra Services ──
  infraServices: {
    filterPlaceholder: (count: number) =>
      `Rechercher (${count} service${count > 1 ? "s" : ""})\u2026`,
    allCategories: "Toutes catégories",
    noService: "Aucun service trouvé",
    category: "Catégorie",
    containers: "Conteneurs Docker",
    setupCost: "Coût setup",
    monthlyCost: "Coût mensuel",
    requiresDocker: "Docker requis",
    requiresDockerHint: "Ce service nécessite un déploiement Docker/VPS — non compatible avec hébergement mutualisé",
    minMaintenance: "Maintenance min.",
    minMaintenanceHint: "Catégorie de maintenance minimum nécessaire pour gérer ce service",
    hostingImpact: "Impact hébergement",
    hostingImpactHint: "RAM supplémentaire nécessaire sur le VPS pour faire tourner ce service",
    ramMb: "RAM (Mo)",
    description: "Description",
    totalSetup: "Total setup",
    totalMonthly: "Total mensuel",
    totalRam: "RAM totale",
    footer: (total: number, categories: number) =>
      `${total} services dans ${categories} catégories`,
  },
} as const;
