//src/lib/generators/traefik.ts
import { readFile, writeFile } from "node:fs/promises";
import { execFile } from "node:child_process";
import { resolve } from "node:path";
import { prisma } from "@/lib/db";
import { localHostBase, localHostForMode, localServiceHost, stackSlugForMode } from "@/lib/docker/names";
import { isServiceEnabledForMode } from "@/lib/generators/compose/services/enabled";

/** Path to the Traefik dynamic config, relative to the monorepo root */
const DYNAMIC_CONFIG_PATH = resolve(
  process.cwd(),
  process.env.TRAEFIK_DYNAMIC_CONFIG ?? "../infra/traefik/conf.d/dynamic.yml",
);

/** Path to TLS certs generated by mkcert */
const CERTS_DIR = resolve(process.cwd(), "../infra/traefik/certs");
const CERT_FILE = resolve(CERTS_DIR, "local-cert.pem");
const KEY_FILE = resolve(CERTS_DIR, "local-key.pem");

interface TraefikRoute {
  /** Unique router/service name */
  name: string;
  /** Host (used for default rule generation) */
  host: string;
  /** Backend URL */
  url: string;
  /** Custom Traefik rule (overrides default Host rule) */
  customRule?: string;
  /** Router priority (higher = matched first) */
  priority?: number;
}

// ── Helpers ──────────────────────────────────────────────────────────────

const LOCAL_ROUTE_MODES = ["dev", "prod-like"] as const;
type LocalRouteMode = (typeof LOCAL_ROUTE_MODES)[number];

function localRouteName(clientSlug: string, projectSlug: string, mode: LocalRouteMode): string {
  return `project-${localHostBase(clientSlug, projectSlug, mode)}`;
}

function pushRoute(
  routes: TraefikRoute[],
  name: string,
  host: string,
  url: string,
  customRule?: string,
  priority?: number,
): void {
  const route: TraefikRoute = { name, host, url };
  if (customRule !== undefined) route.customRule = customRule;
  if (priority !== undefined) route.priority = priority;
  routes.push(route);
}

/**
 * Infer the container port based on tech stack.
 * WordPress = Apache on 80, Next.js = assigned port, etc.
 */
function inferContainerPort(techStack: string | null, port: number): number {
  switch (techStack) {
    case "WORDPRESS":
      return 80;
    default:
      return port;
  }
}

// ── YAML builder ─────────────────────────────────────────────────────────

function buildDynamicYaml(routes: TraefikRoute[]): string {
  const lines: string[] = [
    "# ─── Traefik Dynamic Configuration ───────────────────────────────────",
    "# AUTO-GENERATED by Site Factory. Do not edit manually.",
    `# Last generated: ${new Date().toISOString()}`,
    "",
    "http:",
    "  middlewares:",
    "    # ── Security headers ──────────────────────────────────────────────",
    "    secure-headers:",
    "      headers:",
    "        browserXssFilter: true",
    "        contentTypeNosniff: true",
    "        frameDeny: true",
    "        stsIncludeSubdomains: true",
    "        stsPreload: true",
    "        stsSeconds: 31536000",
    '        customFrameOptionsValue: "SAMEORIGIN"',
    "",
    "    # ── Rate limiting ─────────────────────────────────────────────────",
    "    rate-limit:",
    "      rateLimit:",
    "        average: 100",
    "        burst: 50",
    "",
    "    # ── Custom error page (services non démarrés) ────────────────────",
    "    error-page:",
    "      errors:",
    "        status:",
    '          - "502-504"',
    "        service: error-pages",
    "        query: /",
    "",
    "    # ── Prefix pour catch-all (projet inexistant) ─────────────────────",
    "    not-found-prefix:",
    "      addPrefix:",
    '        prefix: "/not-found"',
  ];

  if (routes.length > 0) {
    lines.push("");
    lines.push("  routers:");

    for (const route of routes) {
      const rule = route.customRule ?? `Host(\`${route.host}\`)`;
      lines.push(`    ${route.name}:`);
      lines.push(`      rule: "${rule}"`);
      if (route.priority !== undefined) {
        lines.push(`      priority: ${String(route.priority)}`);
      }
      lines.push("      entrypoints:");
      lines.push("        - websecure");
      lines.push(`      service: ${route.name}`);
      lines.push("      middlewares:");
      lines.push("        - secure-headers");
      lines.push("        - error-page");
      lines.push("      tls: {}");
    }

    // ── Catch-all router (projet inexistant) ──────────────────────────
    lines.push("");
    lines.push("    # ── Catch-all : projet inexistant ─────────────────────────────");
    lines.push("    catch-all:");
    lines.push('      rule: "HostRegexp(`^.+\\\\.localhost$`)"');
    lines.push("      priority: 1");
    lines.push("      entrypoints:");
    lines.push("        - websecure");
    lines.push("      service: error-pages");
    lines.push("      middlewares:");
    lines.push("        - not-found-prefix");
    lines.push("      tls: {}");

    lines.push("");
    lines.push("  services:");

    // ── Error pages service ──────────────────────────────────────────────
    lines.push("    error-pages:");
    lines.push("      loadBalancer:");
    lines.push("        servers:");
    lines.push('          - url: "http://error-pages:80"');

    for (const route of routes) {
      lines.push(`    ${route.name}:`);
      lines.push("      loadBalancer:");
      lines.push("        servers:");
      lines.push(`          - url: "${route.url}"`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

// ── TLS certificate regeneration ──────────────────────────────────────────

/**
 * Regenerate the mkcert TLS certificate when the host list changes.
 *
 * Chrome/macOS does not honour *.localhost wildcards, so every hostname
 * must be listed explicitly as a SAN entry.  We also keep "localhost"
 * and the infrastructure hosts (traefik, adminer, whoami).
 */
async function regenerateCertIfNeeded(routes: TraefikRoute[]): Promise<void> {
  // Collect every unique hostname that needs a SAN entry
  const allHosts = new Set<string>();
  allHosts.add("localhost");

  // Infrastructure hosts defined in static.yml
  allHosts.add("traefik.localhost");
  allHosts.add("adminer.localhost");
  allHosts.add("whoami.localhost");

  for (const r of routes) {
    allHosts.add(r.host);
  }

  // Build the SAN list sorted for stable comparison
  const sanList = [...allHosts].sort();

  // Compare with existing cert SANs (stored as a comment in the cert dir)
  const sanFile = resolve(CERTS_DIR, ".san-list");
  let existingSans = "";
  try {
    existingSans = await readFile(sanFile, "utf-8");
  } catch {
    // File doesn't exist — first run
  }

  const newSans = sanList.join("\n");
  if (existingSans.trim() === newSans.trim()) return; // No change

  // Regenerate certificate with mkcert
  try {
    await new Promise<void>((ok, fail) => {
      execFile(
        "mkcert",
        ["-cert-file", CERT_FILE, "-key-file", KEY_FILE, ...sanList],
        (error) => {
          if (error) {
            fail(error as Error);
          } else {
            ok();
          }
        },
      );
    });
    await writeFile(sanFile, newSans, "utf-8");

    // Touch tls.yml to force Traefik to reload the certificate via file watcher
    const tlsConfigPath = resolve(CERTS_DIR, "..", "conf.d", "tls.yml");
    try {
      const tlsContent = await readFile(tlsConfigPath, "utf-8");
      await writeFile(tlsConfigPath, tlsContent, "utf-8");
    } catch {
      // Non-fatal
    }

    console.log(`[traefik] TLS cert regenerated with ${String(sanList.length)} SANs`);
  } catch (err) {
    // mkcert not installed or error — non-fatal, cert stays as-is
    console.warn("[traefik] Could not regenerate TLS cert:", err);
  }
}

// ── Public API ────────────────────────────────────────────────────────────

/**
 * Regenerate the Traefik dynamic.yml from all ACTIVE projects with a port.
 * This function is idempotent: calling it multiple times produces the same result
 * for the same database state.
 *
 * For DOCKER projects, also generates routes for ancillary services
 * (phpMyAdmin, Mailpit) based on ProjectConfig flags.
 */
export async function generateTraefikConfig(): Promise<void> {
  const projects = await prisma.project.findMany({
    where: {
      status: "ACTIVE",
      runtime: { port: { not: null } },
    },
    select: {
      slug: true,
      domain: true,
      techStack: true,
      runtime: { select: { port: true } },
      wpConfig: { select: { wpHeadless: true, frontendStack: true } },
      services: { where: { enabled: true }, select: { serviceId: true } },
      client: { select: { slug: true } },
      deployTarget: true,
    },
    orderBy: { slug: "asc" },
  });

  const routes: TraefikRoute[] = [];

  for (const p of projects) {
    const port = p.runtime?.port;
    if (port == null) continue;

    const clientSlug = p.client.slug;
    const isHeadless = p.techStack === "WORDPRESS" && p.wpConfig?.wpHeadless === true;
    const enabledIds = new Set(p.services.map((s) => s.serviceId));
    const containerPort = inferContainerPort(p.techStack, port);

    const mainHosts = LOCAL_ROUTE_MODES.map((mode) => ({
      host: localHostForMode(clientSlug, p.slug, mode),
      nameBase: localRouteName(clientSlug, p.slug, mode),
      stackSlug: stackSlugForMode(p.slug, mode),
    }));

    if (p.domain) {
      mainHosts.push({
        host: p.domain,
        nameBase: `project-${clientSlug}-${p.slug}-domain`,
        stackSlug: stackSlugForMode(p.slug, "prod-like"),
      });
    }

    for (const { host, nameBase, stackSlug } of mainHosts) {
      if (isHeadless) {
        // Headless WP: path-based routing
        // WP backend handles: /wp-json, /wp-admin, /wp-content, /wp-includes, /wp-login.php
        pushRoute(
          routes,
          `${nameBase}-wp`,
          host,
          `http://${stackSlug}:80`,
          `Host(\`${host}\`) && (PathPrefix(\`/wp-json\`) || PathPrefix(\`/wp-admin\`) || PathPrefix(\`/wp-content\`) || PathPrefix(\`/wp-includes\`) || Path(\`/wp-login.php\`) || Path(\`/xmlrpc.php\`))`,
          10, // Higher priority for specific paths
        );
        // Frontend handles everything else
        pushRoute(
          routes,
          nameBase,
          host,
          `http://${stackSlug}-front:${String(port)}`,
          undefined, // Default Host rule
          5, // Lower priority — catch-all
        );
      } else {
        // Standard routing: single container
        pushRoute(routes, nameBase, host, `http://${stackSlug}:${String(containerPort)}`);
      }
    }

    // Ancillary services (also on the proxy network)
    for (const mode of LOCAL_ROUTE_MODES) {
      const nameBase = localRouteName(clientSlug, p.slug, mode);
      const stackSlug = stackSlugForMode(p.slug, mode);
      if (isServiceEnabledForMode("phpmyadmin", enabledIds, p.deployTarget, mode)) {
        pushRoute(
          routes,
          `${nameBase}-pma`,
          localServiceHost("pma", clientSlug, p.slug, mode),
          `http://${stackSlug}-pma:80`,
        );
      }
      if (isServiceEnabledForMode("mailpit", enabledIds, p.deployTarget, mode)) {
        pushRoute(
          routes,
          `${nameBase}-mail`,
          localServiceHost("mail", clientSlug, p.slug, mode),
          `http://${stackSlug}-mailpit:8025`,
        );
      }
    }
  }

  const yaml = buildDynamicYaml(routes);
  await writeFile(DYNAMIC_CONFIG_PATH, yaml, "utf-8");

  // Regenerate TLS certificate if SAN list changed (new sub-sub-domains)
  await regenerateCertIfNeeded(routes);
}
