-- AlterTable
ALTER TABLE `projects` ADD COLUMN `hosting_target` ENUM('SHARED_PHP', 'MANAGED_WORDPRESS', 'CLOUD_STATIC', 'CLOUD_SSR', 'VPS_DOCKER', 'SAAS', 'SPLIT_HEADLESS', 'TO_CONFIRM') NULL,
    ADD COLUMN `hosting_target_back` ENUM('SHARED_PHP', 'MANAGED_WORDPRESS', 'CLOUD_STATIC', 'CLOUD_SSR', 'VPS_DOCKER', 'SAAS', 'SPLIT_HEADLESS', 'TO_CONFIRM') NULL,
    ADD COLUMN `hosting_target_front` ENUM('SHARED_PHP', 'MANAGED_WORDPRESS', 'CLOUD_STATIC', 'CLOUD_SSR', 'VPS_DOCKER', 'SAAS', 'SPLIT_HEADLESS', 'TO_CONFIRM') NULL,
    ADD COLUMN `project_family` ENUM('STATIC_SSG', 'CMS_MONO', 'CMS_HEADLESS', 'COMMERCE_SAAS', 'COMMERCE_SELF_HOSTED', 'COMMERCE_HEADLESS', 'APP_PLATFORM') NULL,
    ADD COLUMN `project_frontend_implementation` ENUM('NEXTJS', 'NUXT', 'ASTRO', 'SVELTEKIT', 'REMIX', 'GATSBY', 'OTHER') NULL,
    ADD COLUMN `project_frontend_implementation_label` VARCHAR(191) NULL,
    ADD COLUMN `project_implementation` ENUM('ASTRO', 'ELEVENTY', 'HUGO', 'JEKYLL', 'GATSBY', 'NEXT_SSG', 'NUXT_SSG', 'WORDPRESS', 'GHOST', 'CRAFT', 'DRUPAL', 'JOOMLA', 'WEBFLOW', 'WORDPRESS_HEADLESS', 'WOOCOMMERCE_HEADLESS', 'STRAPI', 'CONTENTFUL', 'SANITY', 'PRISMIC', 'DIRECTUS', 'STORYBLOK', 'SHOPIFY', 'BIGCOMMERCE', 'WEBFLOW_COMMERCE', 'WOOCOMMERCE', 'PRESTASHOP', 'MAGENTO', 'SHOPWARE', 'SYLIUS', 'SHOPIFY_HEADLESS', 'MEDUSA', 'COMMERCETOOLS', 'SALEOR', 'NEXTJS', 'NUXT', 'SVELTEKIT', 'REMIX', 'OTHER') NULL,
    ADD COLUMN `project_implementation_label` VARCHAR(191) NULL;
