import type { ComposeMode, ComposeProjectInput } from "../types";
import { stackSlugForMode } from "@/lib/docker";

export function composeHeader(input: ComposeProjectInput, mode: ComposeMode): string {
  const stackSlug = stackSlugForMode(input.projectSlug, mode);
  const modeLabel =
    mode === "dev"
      ? "Développement local"
      : mode === "prod-like"
        ? "Prod-like (simulation production)"
        : "Production";

  const lines = [
    "# Auto-generated by Site Factory",
    `# Project: ${input.projectSlug} (${input.type})`,
    `# Client: ${input.clientSlug}`,
    `# Stack: ${input.techStack ?? "none"}`,
    `# Mode: ${modeLabel}`,
    `# Target: ${input.deployTarget}`,
  ];

  if (input.wpConfig?.wpHeadless) {
    lines.push(`# WP Headless: ${input.wpConfig.frontendStack ?? "NEXTJS"} frontend`);
  }

  lines.push(`# Generated: ${new Date().toISOString()}`, "", `name: ${stackSlug}`, "");
  return lines.join("\n");
}
