import { describe, it, expect } from "vitest";
import { wordpressCompose, wpSetupScript } from "./compose-wordpress";
import type { ComposeProjectInput } from "./types";

function makeWpInput(
  overrides?: Partial<ComposeProjectInput>,
): ComposeProjectInput {
  return {
    projectSlug: "mon-blog",
    clientSlug: "acme",
    port: 3001,
    domain: null,
    type: "VITRINE",
    techStack: "WORDPRESS",
    deployTarget: "DOCKER",
    devMode: "DEV_COMFORT",
    enabledServiceIds: new Set<string>(),
    database: {
      dbType: "MARIADB",
      dbVersion: "11",
      dbName: "wp_mon_blog",
      dbUser: "wordpress",
      dbPassword: "secret",
    },
    wpConfig: {
      phpVersion: "8.3",
      wpHeadless: false,
      frontendStack: null,
      wpSiteTitle: "Mon Blog",
      wpAdminUser: "admin",
      wpAdminPassword: "admin",
      wpAdminEmail: "admin@example.com",
      wpPermalinkStructure: null,
      wpDefaultPages: null,
      wpPlugins: null,
      wpTheme: null,
    },
    nextConfig: null,
    ...overrides,
  };
}

describe("wordpressCompose", () => {
  describe("dev mode basics", () => {
    const yaml = wordpressCompose(makeWpInput(), "dev");

    it("starts with auto-generated header", () => {
      expect(yaml).toContain("# Auto-generated by Site Factory");
    });

    it("sets correct compose name", () => {
      expect(yaml).toContain("name: mon-blog-dev");
    });

    it("uses correct WordPress image", () => {
      expect(yaml).toContain("image: wordpress:php8.3-apache");
    });

    it("includes MariaDB service", () => {
      expect(yaml).toContain("mon-blog-dev-db:");
      expect(yaml).toContain("image: mariadb:11");
    });

    it("sets WP environment variables", () => {
      expect(yaml).toContain('WORDPRESS_DB_HOST: "mon-blog-dev-db"');
      expect(yaml).toContain('WORDPRESS_DB_NAME: "wp_mon_blog"');
      expect(yaml).toContain('WORDPRESS_DB_USER: "wordpress"');
      expect(yaml).toContain('WORDPRESS_DB_PASSWORD: "secret"');
      expect(yaml).toContain('WP_TITLE: "Mon Blog"');
      expect(yaml).toContain('WP_ADMIN_USER: "admin"');
    });

    it("includes wp-setup.sh volume mount", () => {
      expect(yaml).toContain("wp-setup.sh:/usr/local/bin/wp-setup.sh:ro");
    });

    it("includes wp-content volume mount in dev mode", () => {
      expect(yaml).toContain("wp/wp-content:/var/www/html/wp-content");
    });

    it("includes wp-config.extra.local.php mount in dev", () => {
      expect(yaml).toContain("wp-config.extra.local.php:/var/www/html/wp-config.extra.php:ro");
    });

    it("includes theme source mount for non-headless", () => {
      expect(yaml).toContain("sf-tt5:/opt/sf-themes/sf-tt5:ro");
    });

    it("uses localhost host in dev", () => {
      expect(yaml).toContain('WP_URL: "https://acme-mon-blog-dev.localhost"');
    });

    it("includes extra_hosts for dev", () => {
      expect(yaml).toContain("extra_hosts:");
      expect(yaml).toContain("acme-mon-blog-dev.localhost:host-gateway");
    });

    it("declares volumes and networks", () => {
      expect(yaml).toContain("volumes:");
      expect(yaml).toContain("mon-blog-dev_wp_data:");
      expect(yaml).toContain("mon-blog-dev_db_data:");
      expect(yaml).toContain("networks:");
      expect(yaml).toContain("proxy:");
      expect(yaml).toContain("mon-blog-dev_internal:");
    });
  });

  describe("custom domain", () => {
    const yaml = wordpressCompose(
      makeWpInput({ domain: "www.monsite.fr" }),
      "dev",
    );

    it("uses custom domain instead of localhost", () => {
      expect(yaml).toContain('WP_URL: "https://www.monsite.fr"');
    });
  });

  describe("prod-like mode", () => {
    const yaml = wordpressCompose(makeWpInput(), "prod-like");

    it("sets correct compose name", () => {
      expect(yaml).toContain("name: mon-blog-prod-like");
    });

    it("uses prod-like wp-config.extra", () => {
      expect(yaml).toContain("wp-config.extra.prod-like.php:/var/www/html/wp-config.extra.php:ro");
    });

    it("sets APP_ENV to prod-like", () => {
      expect(yaml).toContain('APP_ENV: "prod-like"');
    });
  });

  describe("prod mode", () => {
    const yaml = wordpressCompose(makeWpInput(), "prod");

    it("sets correct compose name (bare slug)", () => {
      expect(yaml).toContain("name: mon-blog");
    });

    it("does not include dev volumes", () => {
      expect(yaml).not.toContain("wp-content:/var/www/html/wp-content");
      expect(yaml).not.toContain("wp-config.extra.local.php");
    });

    it("does not include extra_hosts", () => {
      expect(yaml).not.toContain("extra_hosts:");
    });

    it("sets APP_ENV to production", () => {
      expect(yaml).toContain('APP_ENV: "production"');
    });
  });

  describe("optional services", () => {
    it("adds redis env vars when redis enabled", () => {
      const yaml = wordpressCompose(
        makeWpInput({ enabledServiceIds: new Set(["redis"]) }),
        "dev",
      );
      expect(yaml).toContain('WP_REDIS_HOST: "mon-blog-dev-redis"');
      expect(yaml).toContain("mon-blog-dev-redis:");
      expect(yaml).toContain("image: redis:7-alpine");
      expect(yaml).toContain("mon-blog-dev_redis_data:");
    });

    it("adds mailpit env vars when mailpit enabled", () => {
      const yaml = wordpressCompose(
        makeWpInput({ enabledServiceIds: new Set(["mailpit"]) }),
        "dev",
      );
      expect(yaml).toContain('WORDPRESS_SMTP_HOST: "mon-blog-dev-mailpit"');
      expect(yaml).toContain('WORDPRESS_SMTP_PORT: "1025"');
      expect(yaml).toContain("mon-blog-dev-mailpit:");
    });

    it("adds phpmyadmin when enabled with MariaDB", () => {
      const yaml = wordpressCompose(
        makeWpInput({ enabledServiceIds: new Set(["phpmyadmin"]) }),
        "dev",
      );
      expect(yaml).toContain("mon-blog-dev-pma:");
      expect(yaml).toContain("image: phpmyadmin:latest");
    });

    it("adds elasticsearch env var when enabled", () => {
      const yaml = wordpressCompose(
        makeWpInput({ enabledServiceIds: new Set(["elasticsearch"]) }),
        "dev",
      );
      expect(yaml).toContain(
        'ELASTICSEARCH_URL: "http://mon-blog-dev-elasticsearch:9200"',
      );
    });

    it("adds minio env vars when enabled", () => {
      const yaml = wordpressCompose(
        makeWpInput({ enabledServiceIds: new Set(["minio"]) }),
        "dev",
      );
      expect(yaml).toContain('S3_ENDPOINT: "http://mon-blog-dev-minio:9000"');
      expect(yaml).toContain('S3_ACCESS_KEY: "minioadmin"');
    });
  });

  describe("headless mode", () => {
    const yaml = wordpressCompose(
      makeWpInput({
        wpConfig: {
          phpVersion: "8.3",
          wpHeadless: true,
          frontendStack: "NEXTJS",
          wpSiteTitle: "Mon Blog",
          wpAdminUser: "admin",
          wpAdminPassword: "admin",
          wpAdminEmail: "admin@example.com",
          wpPermalinkStructure: null,
          wpDefaultPages: null,
          wpPlugins: null,
          wpTheme: null,
        },
      }),
      "dev",
    );

    it("adds frontend container", () => {
      expect(yaml).toContain("mon-blog-dev-front:");
      expect(yaml).toContain("image: node:");
      expect(yaml).toContain("command: npm start");
    });

    it("sets WORDPRESS_API_URL on frontend", () => {
      expect(yaml).toContain(
        'WORDPRESS_API_URL: "http://mon-blog-dev/wp-json"',
      );
    });

    it("does not mount theme source for headless", () => {
      expect(yaml).not.toContain("sf-tt5:/opt/sf-themes/sf-tt5:ro");
    });
  });

  describe("DB fallback when database is null", () => {
    const yaml = wordpressCompose(
      makeWpInput({ database: null }),
      "dev",
    );

    it("falls back to MariaDB defaults", () => {
      expect(yaml).toContain("image: mariadb:");
      expect(yaml).toContain('WORDPRESS_DB_NAME: "wp_mon_blog"');
      expect(yaml).toContain('WORDPRESS_DB_USER: "wordpress"');
      expect(yaml).toContain('WORDPRESS_DB_PASSWORD: "wordpress"');
    });
  });
});

// ── wpSetupScript ────────────────────────────────────────────────────

describe("wpSetupScript", () => {
  describe("default options", () => {
    const script = wpSetupScript();

    it("starts with shebang", () => {
      expect(script).toMatch(/^#!/);
    });

    it("uses set -euo pipefail", () => {
      expect(script).toContain("set -euo pipefail");
    });

    it("installs WP-CLI", () => {
      expect(script).toContain("wp-cli.phar");
    });

    it("runs wp core install", () => {
      expect(script).toContain("wp core install");
    });

    it("sets French language", () => {
      expect(script).toContain("wp language core install fr_FR");
      expect(script).toContain("wp site switch-language fr_FR");
    });

    it("removes default plugins", () => {
      expect(script).toContain("wp plugin delete akismet hello");
    });

    it("ends with apache2-foreground", () => {
      expect(script).toContain("exec apache2-foreground");
    });

    it("uses default permalink structure", () => {
      expect(script).toContain('wp rewrite structure "/%postname%/"');
    });
  });

  describe("custom permalink", () => {
    const script = wpSetupScript({ permalink: "/%year%/%postname%/" });

    it("uses custom permalink", () => {
      expect(script).toContain(
        'wp rewrite structure "/%year%/%postname%/"',
      );
    });
  });

  describe("preset pages", () => {
    const script = wpSetupScript({
      pages: [
        { title: "Accueil", slug: "accueil", isFrontPage: true },
        { title: "Contact", slug: "contact" },
        { title: "À propos", slug: "a-propos" },
      ],
    });

    it("creates pages with wp post create", () => {
      expect(script).toContain('--post_title="Accueil"');
      expect(script).toContain('--post_name="accueil"');
      expect(script).toContain('--post_title="Contact"');
      expect(script).toContain('--post_title="À propos"');
    });

    it("captures front page ID", () => {
      expect(script).toContain("FRONT_PAGE_ID=$(wp post create");
    });

    it("sets show_on_front to page", () => {
      expect(script).toContain('wp option update show_on_front "page"');
    });

    it("sets page_on_front", () => {
      expect(script).toContain(
        'wp option update page_on_front "$FRONT_PAGE_ID"',
      );
    });
  });

  describe("plugins", () => {
    const script = wpSetupScript({
      plugins: [
        { slug: "advanced-custom-fields", activate: true },
        { slug: "query-monitor", activate: false },
      ],
    });

    it("installs plugins with --activate when requested", () => {
      expect(script).toContain(
        "wp plugin install advanced-custom-fields --activate",
      );
    });

    it("installs plugins without --activate when disabled", () => {
      expect(script).toContain("wp plugin install query-monitor --allow-root");
      expect(script).not.toContain(
        "wp plugin install query-monitor --activate",
      );
    });
  });

  describe("theme", () => {
    const script = wpSetupScript({ theme: "sf-tt5" });

    it("activates theme if directory exists", () => {
      expect(script).toContain('if [ -d "wp-content/themes/sf-tt5" ]');
      expect(script).toContain("wp theme activate sf-tt5");
    });

    it("installs theme if not present", () => {
      expect(script).toContain("wp theme install sf-tt5 --activate");
    });
  });

  describe("no pages / no plugins / no theme", () => {
    const script = wpSetupScript({
      pages: [],
      plugins: [],
      theme: null,
    });

    it("does not contain page creation commands", () => {
      expect(script).not.toContain("FRONT_PAGE_ID");
      expect(script).not.toContain("show_on_front");
    });

    it("does not contain plugin install commands", () => {
      expect(script).not.toContain("wp plugin install");
    });

    it("does not contain custom theme install (only parent twentytwentyfive)", () => {
      // twentytwentyfive parent theme is always installed as a safety net for sf-tt5
      expect(script).toContain("wp theme install twentytwentyfive");
      // But no custom theme install/activate block should be present
      expect(script).not.toContain('wp theme install sf-tt5');
    });
  });
});
