import { describe, it, expect } from "vitest";
import { nextjsCompose } from "./compose-nextjs";
import type { ComposeProjectInput } from "./types";

function makeNextInput(
  overrides?: Partial<ComposeProjectInput>,
): ComposeProjectInput {
  return {
    projectSlug: "my-app",
    clientSlug: "acme",
    port: 3010,
    domain: null,
    type: "APP",
    techStack: "NEXTJS",
    deployTarget: "DOCKER",
    devMode: "DEV_COMFORT",
    enabledServiceIds: new Set<string>(),
    database: null,
    wpConfig: null,
    nextConfig: {
      nodeVersion: "22",
      envVarsJson: null,
    },
    ...overrides,
  };
}

describe("nextjsCompose", () => {
  describe("dev mode basics", () => {
    const yaml = nextjsCompose(makeNextInput(), "dev");

    it("starts with header", () => {
      expect(yaml).toContain("# Auto-generated by Site Factory");
    });

    it("sets correct compose name", () => {
      expect(yaml).toContain("name: my-app-dev");
    });

    it("uses correct node image", () => {
      expect(yaml).toContain("image: node:22-alpine");
    });

    it("sets PORT env var", () => {
      expect(yaml).toContain('PORT: "3010"');
    });

    it("sets NODE_ENV to development for dev mode", () => {
      expect(yaml).toContain('NODE_ENV: "development"');
    });

    it("mounts project directory at /app", () => {
      expect(yaml).toContain("projects/acme/my-app:/app");
    });

    it("uses proxy network", () => {
      expect(yaml).toContain("- proxy");
    });

    it("does not create internal network without services", () => {
      expect(yaml).not.toContain("my-app-dev_internal:");
    });
  });

  describe("prod-like mode", () => {
    const yaml = nextjsCompose(makeNextInput(), "prod-like");

    it("sets NODE_ENV to production", () => {
      expect(yaml).toContain('NODE_ENV: "production"');
    });

    it("uses prod-like slug", () => {
      expect(yaml).toContain("name: my-app-prod-like");
    });
  });

  describe("with PostgreSQL database", () => {
    const yaml = nextjsCompose(
      makeNextInput({
        database: {
          dbType: "POSTGRESQL",
          dbVersion: "17",
          dbName: "mydb",
          dbUser: "appuser",
          dbPassword: "pgpass",
        },
      }),
      "dev",
    );

    it("includes database service", () => {
      expect(yaml).toContain("my-app-dev-db:");
      expect(yaml).toContain("image: postgres:17-alpine");
    });

    it("sets DATABASE_URL env var", () => {
      expect(yaml).toContain(
        'DATABASE_URL: "postgresql://appuser:pgpass@my-app-dev-db:5432/mydb"',
      );
    });

    it("adds depends_on with healthcheck", () => {
      expect(yaml).toContain("depends_on:");
      expect(yaml).toContain("condition: service_healthy");
    });

    it("creates internal network", () => {
      expect(yaml).toContain("my-app-dev_internal:");
    });

    it("declares db volume", () => {
      expect(yaml).toContain("my-app-dev_db_data:");
    });
  });

  describe("optional services", () => {
    it("adds redis env var and service", () => {
      const yaml = nextjsCompose(
        makeNextInput({ enabledServiceIds: new Set(["redis"]) }),
        "dev",
      );
      expect(yaml).toContain('REDIS_URL: "redis://my-app-dev-redis:6379"');
      expect(yaml).toContain("my-app-dev-redis:");
      expect(yaml).toContain("my-app-dev_redis_data:");
    });

    it("adds mailpit env vars", () => {
      const yaml = nextjsCompose(
        makeNextInput({ enabledServiceIds: new Set(["mailpit"]) }),
        "dev",
      );
      expect(yaml).toContain('SMTP_HOST: "my-app-dev-mailpit"');
      expect(yaml).toContain('SMTP_PORT: "1025"');
    });

    it("adds elasticsearch env var", () => {
      const yaml = nextjsCompose(
        makeNextInput({ enabledServiceIds: new Set(["elasticsearch"]) }),
        "dev",
      );
      expect(yaml).toContain(
        'ELASTICSEARCH_URL: "http://my-app-dev-elasticsearch:9200"',
      );
    });

    it("adds meilisearch env var", () => {
      const yaml = nextjsCompose(
        makeNextInput({ enabledServiceIds: new Set(["meilisearch"]) }),
        "dev",
      );
      expect(yaml).toContain(
        'MEILI_HOST: "http://my-app-dev-meilisearch:7700"',
      );
    });

    it("adds minio env vars", () => {
      const yaml = nextjsCompose(
        makeNextInput({ enabledServiceIds: new Set(["minio"]) }),
        "dev",
      );
      expect(yaml).toContain('S3_ENDPOINT: "http://my-app-dev-minio:9000"');
      expect(yaml).toContain('S3_ACCESS_KEY: "minioadmin"');
    });

    it("adds rabbitmq env var", () => {
      const yaml = nextjsCompose(
        makeNextInput({ enabledServiceIds: new Set(["rabbitmq"]) }),
        "dev",
      );
      expect(yaml).toContain(
        'AMQP_URL: "amqp://guest:guest@my-app-dev-rabbitmq:5672"',
      );
    });

    it("creates internal network when services are enabled", () => {
      const yaml = nextjsCompose(
        makeNextInput({ enabledServiceIds: new Set(["redis"]) }),
        "dev",
      );
      expect(yaml).toContain("my-app-dev_internal:");
    });
  });

  describe("custom env vars", () => {
    const yaml = nextjsCompose(
      makeNextInput({
        nextConfig: {
          nodeVersion: "20",
          envVarsJson: JSON.stringify({
            CUSTOM_VAR: "hello",
            API_KEY: "abc123",
          }),
        },
      }),
      "dev",
    );

    it("uses specified node version", () => {
      expect(yaml).toContain("image: node:20-alpine");
    });

    it("injects custom env vars", () => {
      expect(yaml).toContain('CUSTOM_VAR: "hello"');
      expect(yaml).toContain('API_KEY: "abc123"');
    });
  });

  describe("no database", () => {
    const yaml = nextjsCompose(makeNextInput({ database: null }), "dev");

    it("does not include depends_on", () => {
      expect(yaml).not.toContain("depends_on:");
    });

    it("does not include db service", () => {
      expect(yaml).not.toContain("my-app-dev-db:");
    });

    it("does not include DATABASE_URL", () => {
      expect(yaml).not.toContain("DATABASE_URL:");
    });
  });
});
